### ISSUE TITLE
Can't open particular .torrent file

### ISSUE THREAD

**Issue by student13371** [GerryFerdinandus/bittorrent-tracker-editor#10]
Bittorrent tracker editor v1.31 can't open particular .torrent file. 

However that .torrent file is OK and uTorrent opens it just fine.

This .torrent file size is quite big 1.47 MB.

I've uploaded this .torrent file. Use one of the links:

https://goo.gl/tjzSzb

http://www56.zippyshare.com/v/XW5iUaGj/file.html

**Comment by GerryFerdinandus** [comment]
Thanks for reporting this issue.
A new 1.32.beta version can be downloaded.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by student13371** [comment]
New 1.32.beta version opens and edits this particular .torrent file just fine.

Thank you.
