### ISSUE TITLE
tracker.thepiratebay.org unsupported

### ISSUE THREAD

**Issue by student13371** [GerryFerdinandus/bittorrent-tracker-editor#11]
1.32 BETA and older versions act odd with two thepiratebay.org trackers:

http://tracker.thepiratebay.org/announce
udp://tracker.thepiratebay.org:80/announce

These trackers are automatically unchecked:

<img width="327" alt="tpb1" src="https://cloud.githubusercontent.com/assets/12573989/9288185/f83f7cd4-4342-11e5-94db-a52f407b2931.png">

Even if those trackers are manually checked to be included, those trackers still aren't included and are lost after Update torrent:

<img width="328" alt="tpb2" src="https://cloud.githubusercontent.com/assets/12573989/9288188/12bc3502-4343-11e5-96df-c98b3b4bdfd3.png">

I understand that these trackers aren't alive at the moment, but such behavior is still bad because:

1. It's odd to exclude some particular trackers (even if those trackers aren't alive) and leave checked some other trackers that are dead too.

2. User manually chooses to include these trackers, but those trackers aren't included and no prompt is given.

3. openbittorrent.com and demonoid trackers were dead for a while, but resurrected. The same might happen with any other tracker, including thepiratebay.org too.

I wonder why this issue happened.

Is it something unique to these 2 thepiratebay.org trackers or are there more unsupported trackers like these 2?

Here's the link to a sample .torrent file which has thepiratebay.org tracker:
https://goo.gl/wDSFf6

**Comment by GerryFerdinandus** [comment]
1)
Trackers can automatically be removed by the tracker list inside the file remove_trackers.txt

2)
These trackers list inside the remove_torrent.txt overrule everything. The trackers inside this file should NEVER be inserted into the torrent files.

3)(todo)
The two trackers are inside remove_trackers.txt are just an example. 
I will change the default example tracker to:
udp://tracker.trackerhoneypot.com:80

4)
The main purpose of the file remove_torrent.txt is to remove these trackers without ANY exception. User can put here trackers that they do not trust. User can delete this remove_trackers.txt file. And no trackers will be forbidden.

**Comment by student13371** [comment]
Thanks for clarification.

Yes, it would be better if by default **remove_trackers.txt** would include a fake tracker example, something like **udp://tracker.trackerhoneypot.com:80**
