### ISSUE TITLE
[Wishlist] Add trackers to multiple .torrent files without changing existing unique, individual trackers

### ISSUE THREAD

**Issue by student13371** [GerryFerdinandus/bittorrent-tracker-editor#12]
This isn't a bug. This is a feature request.

Currently when adding trackers to multiple .torrent files, user is given a list of "Present trackers in all torrent files". Those trackers that are checked in this list are added to EVERY .torrent file and those trackers that aren't checked are REMOVED from those .torrent files that originally INCLUDED those trackers. This ultimately leads to creation of .torrent files with exactly the same list of trackers. Everything is OK. This is a handy feature.

However, there are cases when user wants to keep the unique trackers in .torrent files and just add some additional trackers to multiple .torrent files. For instance, you have 1000 .torrent files with different lists of trackers and simply want to add a couple of new, same trackers to all of them, but you don't want all of those .torrent files to have an exactly the same list of trackers showed under "Present trackers in all torrent files" list after an Update. 

This feature could be called something like "Add trackers to multiple .torrent files without changing the existing trackers". In other words, feature that allows to add new trackers to multiple .torrent files without touching the existing unique, individual trackers and without creation of .torrent files with exactly the same list of trackers.

**Comment by GerryFerdinandus** [comment]
Thanks for the feature request.
A new V1.32.0.RC.2 version can be downloaded.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by GerryFerdinandus** [comment]
This issue fixed
