### ISSUE TITLE
Sometimes trackers are not removed/added from a torrent

### ISSUE THREAD

**Issue by Uplink10** [GerryFerdinandus/bittorrent-tracker-editor#14]
I had a lot of .torrent files in one folder and I wanted to remove all trackers in them and add the trackers that I had in the text file. But after I tried to do that nothing happened so I copied one .torrent file and tried to do the same to this torrent file and still nothing happened. But when I opened another set of .torrent files everything worked.
Here is a pack of this torrent files which tracker editor doesn't edit:

https://mega.nz/#!PghUAAxC!Sj-cSpl-LJeRmXyFNO9ZRQvuHi_eiKy6bHoXJMTubUk

**Comment by GerryFerdinandus** [comment]
Thanks for reporting this issue.

I have check your torrent files. There are 16 torrent files inside the folder. 
8 of them have 'read-only' file attibute ACTIVE, tracker editor can not modifiy these 8 files.
After I remove these 'read-only' attibute, all the 16 files works as expected.

Can you verify that your local torrent files does NOT have 'read-only' file attibute set to ACTIVE.  
Ctrl-A -> right mouse -> properties

TODO:
I must add a warning popup if some torrent files have read-only attibute active.

**Comment by Uplink10** [comment]
If I remove Read-only everything works fine, thank you. This was such a mistery to me.

**Comment by GerryFerdinandus** [comment]
Thanks for the feedback. I have updated the source code to give a warning if torrent files are read-only files.
