### ISSUE TITLE
不能通过拖入文件打开 (Can not be opened by dragging a file)

### ISSUE THREAD

**Issue by wdssmq** [GerryFerdinandus/bittorrent-tracker-editor#17]
![](http://t1.qpic.cn/mblogpic/46191abd76011894b1c2/460)

Error: Can not read torrent. D:\Videos\Mower.Minions.2016.720p.BluRay.x264-FLAME.torrent
ERROR: No torrent file selected

**Comment by GerryFerdinandus** [comment]
There are two issues here:
 1) Drag a file/directory to the shortcut link will start the program in console mode. This is not what a user expect. The program should start in windows mode.
 2) The torrent file can not be read by the program for some unknown reason. I do not know what is wrong with this torrent file. Can the torrent file be open by other torrent programs? Or by tracker editor in 'normal' windows mode?

I will fix start in 'normal' windows mode at drag/drop to 'shortcut'

**Comment by GerryFerdinandus** [comment]
Drag to shortcut link is fixed.
This issue fixed in release V1.32.0-RC.5
