### ISSUE TITLE
[Wishlist] Randomize tracker order for each torrent file

### ISSUE THREAD

**Issue by kilves76** [GerryFerdinandus/bittorrent-tracker-editor#19]
Would be nice if there was a -U option to randomize the tracker list order for each torrent file in order to load balance tracker traffic. Options to randomize tracker groups (double spaced), randomize the group (single spaced), maybe a third option for both.

For example, a single spaced list randomized for each torrent, with a reasonably even random distribution, each tracker would only receive (1/totaltrackers)*amounttorrents updates at any one time.

**Comment by GerryFerdinandus** [comment]
There is a new release V1.32.0-RC.5

There is already a sort tracker list torrent option.
Now I have also added randomize tracker selection: -U7 
This function is also available under update menu item.
