### ISSUE TITLE
Can't accept trackers end with "socket"

### ISSUE THREAD

**Issue by imtube** [GerryFerdinandus/bittorrent-tracker-editor#24]
Some trackers like that:

wss://xxx.xxx/tracker/socket

can not be accepted

**Comment by GerryFerdinandus** [comment]
Thanks for reporting this issue.
A new 1.33.0.beta.3 version can be downloaded.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by anonymiz** [comment]
will this script available as php script to integrate to my existing project or site

**Comment by GerryFerdinandus** [comment]
There will be no php script version of this project.
