### ISSUE TITLE
add support for '/announce.php'

### ISSUE THREAD

**Issue by drewbitt** [GerryFerdinandus/bittorrent-tracker-editor#27]
You cannot add a tracker without the tracker url ending in /announce currently. However, a few (private) sites use site.com/announce.php announces. Once uploaded you get your unique announce url, but until then they require the announce me site.com/announce.php. 

Allow the user to enter a tracker not ending in /announce

**Comment by GerryFerdinandus** [comment]
Thanks for reporting this issue.

To check for posible copy and paste error, the program look at the begin and the end of the URL line.
Must begin with http://, udp:// etc and end with /announce
If the line begin and end are correct then there should be no copy and paste error.

---

There are two posible solution:
1. remove the check for /announce
2. accept /announce and /announce.php

Solution 1.
Downside is the posible copy and paste error at the end of the line.
This will downgrade the robustness of the program.

Solution 2.
Add extra check in the program for /announce.php, maybe in the future there are more exception needed.

**I will implement solution number 2: accept /announce and /announce.php**

---

Some example list with /announce and /announce.php
https://github.com/ngosang/trackerslist/blob/master/trackers_all.txt
https://github.com/ngosang/trackerslist/blob/master/blacklist.txt

**Comment by GerryFerdinandus** [comment]
A new 1.33.0.beta.5 version can be downloaded.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by drewbitt** [comment]
Seems to work.

**Comment by ChaoticNeutralCzech** [comment]
Some trackers don't follow this, either. I will not say which tracker it is but the announce URL pattern is `https://exampletracker.com/announce/deadbeefdeadbeefdeadbeefdeadbeef` (may differ per user)
