### ISSUE TITLE
For Private Tracker, ERROR: Tracker URL must end with /announce or /announce.php

### ISSUE THREAD

**Issue by waldens** [GerryFerdinandus/bittorrent-tracker-editor#31]
Mind add support for private tracker?

![Screenshot](https://ae01.alicdn.com/kf/HTB1BxgsXEGF3KVjSZFv762_nXXaN.png)

#30 is closed and I cannot reopen it so open a new one.

**Comment by GerryFerdinandus** [comment]
Thanks for the issue report.
A new V1.33.0.RC.6 version can be downloaded.

There is a new tab page for private torrent, where you can disable the announce check.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by ytr968** [comment]
Not my submitted issue, but can confirm that the announce check disabling works.
