### ISSUE TITLE
Source Tag

### ISSUE THREAD

**Issue by ytr968** [GerryFerdinandus/bittorrent-tracker-editor#34]
Is it possible to add an option to add a source tag on the Tracker Editor? In addition to the tracker URLs itself, many trackers require the torrent file to also have a certain source tag under Info for the torrent to register. Many thanks for all of your work!

**Comment by GerryFerdinandus** [comment]
Thanks for the issue report.
A new V1.33.0.RC.6 version can be downloaded.

There is a new tab page for private torrent, where you can enter the source tag.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by ytr968** [comment]
Worked perfectly--thank you!
