### ISSUE TITLE
newTrackOn functions broken; error message: "Can not downloading the trackers from internet"

### ISSUE THREAD

**Issue by user23108947023948** [GerryFerdinandus/bittorrent-tracker-editor#46]
### What steps will reproduce the problem? ###

Try to use any of the newTrackOn related functions. 

### What is the expected output? What do you see instead? ###

It's supposed to communicate with newTrackOn, but instead you get an error message: "Can not downloading the trackers from internet"

### What version of the product are you using. (Please use the latest version of bittorrent-tracker-editor and your torrent client) ###

1.33.0 beta 5

###  On what operating system? ###

Linux Mint 20

### Add a modified sintel torrent files example to reproduce the issue. [Download from Github: sintel](https://github.com/GerryFerdinandus/bittorrent-tracker-editor/tree/master/test_torrent) ###

No

**Comment by GerryFerdinandus** [comment]
This is the same type of issue as described [here](https://github.com/GerryFerdinandus/bittorrent-tracker-editor/issues/39)
You cab download the latest beta version via [snap](https://snapcraft.io/bittorrent-tracker-editor)

**Comment by user23108947023948** [comment]
I'm a Linux Mint user and the distro doesn't support snaps, I think because the server-side implementation is not FOSS.  I'd be willing to make a financial contribution if it would be possible to also release this in a Mint-compatible format like a Flatpak or .deb file. I  believe AppImage is also supported.  Let me know what an appropriate donation would look like for that.

**Comment by GerryFerdinandus** [comment]
It is not a donation issue. As quick work around there is a new download. You can try that.
[Download: trackereditor_linux_amd64_fix_issue_39.zip
](https://github.com/GerryFerdinandus/bittorrent-tracker-editor/releases/tag/1.33.0.beta.6)

**Comment by GerryFerdinandus** [comment]
I'm closing this issue as it's already implemented (Flatpak and AppImage) and released. Thanks for your suggestion.
