### ISSUE TITLE
Trying to figure out the tracker formatting in the editor app vs torrent

### ISSUE THREAD

**Issue by WanhedaNC** [GerryFerdinandus/bittorrent-tracker-editor#47]
So I'm using v1.33.0 B6 on Win11H (21H2), after I update both tracker sources, it shows all the trackers in the Add new trackers with no problem. Maybe this was addressed somewhere already and I just missed it, but with it showing all of the new trackers one per line and no white space between each line, wouldn't that add all of the trackers into the same tier if I were to update the torrents as is? If so, is there a setting somewhere to separate them and probably a better question, is it better to have them all in one tier or is it better to have 30+ individual tiers? Thanks in advance.

**Comment by GerryFerdinandus** [comment]
@WanhedaNC 
_it shows all new trackers one per line and no white space between each line,_ that's right. But internally, the editor can **only work with different tiers.** You can check/verify the torrent file with the final result with other editors.

To optimize findability,  30+ individual tiers should be used. And the torrent program should always publish all tiers.

This program is not suitable for single-tier torrent concept.

**Comment by WanhedaNC** [comment]
Thanks for the reply. I figured that there was a way to make that work but I had forgotten about that setting for the individual announce so I really appreciate the nudge back on course. That's one of the downfalls in having something as granular as libtorrent can be; forget one little checkbox somewhere and it's cats and dogs, sleeping together… mass hysteria lol.
