### ISSUE TITLE
Hi, Mads from SchemaStore.org here

### ISSUE THREAD

**Issue by madskristensen** [GerryFerdinandus/bittorrent-tracker-editor#48]
Hi Gerry,

I don't know how else to contact you, so this is my best attempt :)

Just wanted to thank you so much for all your work on SchemaStore.org. I've wanted to reach out to you several times, but never thought of using GitHub issues, so this is the first time I'm successful (hopefully). My email is madsk at microsoft com. Please drop me a line if you don't mind.

**Comment by GerryFerdinandus** [comment]
@madskristensen 
Already sent an email. Let me know if you don't receive it due to spam filter.
