### ISSUE TITLE
Handle dark theme on MacOS.

### ISSUE THREAD

**Issue by rquadling** [GerryFerdinandus/bittorrent-tracker-editor#49]
### What steps will reproduce the problem? ###

Open app

### What is the expected output? What do you see instead? ###

Handle dark theme. Instead, some things are unreadable! 
<img width="205" alt="image" src="https://user-images.githubusercontent.com/12801/232324265-be482373-c6ac-4f33-bf07-869f69578c82.png">

### What version of the product are you using. (Please use the latest version of bittorrent-tracker-editor and your torrent client) ###

v1.33

###  On what operating system? ###

MacOS 12.6.3 (Monterey)

### Please provide any additional information below. ###

This was just from opening the app and clicking around. No specific torrent files needed to visualize the issue.

**Comment by GerryFerdinandus** [comment]
Thanks for reporting the problem. It is now fixed in the latest released software.
![Screenshot 2023-11-18 at 00 57 25](https://github.com/GerryFerdinandus/bittorrent-tracker-editor/assets/6232089/6aaac016-63e2-4c7a-9af8-eb86a3429e48)
