### ISSUE TITLE
Any plans to update to gtk3 ?

### ISSUE THREAD

**Issue by luzpaz** [GerryFerdinandus/bittorrent-tracker-editor#50]
Current dependency on gtk2 requires installing a whole host of old 3rd-party dependencies. So just asking if it's on the roadmap ?

**Comment by GerryFerdinandus** [comment]
No plan to upgrade to a newer GTK version.
The [graphics library](https://wiki.lazarus.freepascal.org/Roadmap) I used does not support GTK3 or GTK4.

GTK3 is also not present in the [current minimum supported list](https://forum.lazarus.freepascal.org/index.php/topic,65612.0.html?PHPSESSID=cjth32qlbm1q65bln4bp9stu14).
**FreeBSD/Linux:**
  gtk 2.24 for gtk2, qt4.5 for qt, qt5.6 for qt5, Qt6.2 for qt6, 32 or 64bit.

In the future I will add qt5 and qt6 release build for users who don't use 'Snapcraft' or 'Flathub'
