### ISSUE TITLE
Tracker list rearranged in alphabetical order

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GerryFerdinandus/bittorrent-tracker-editor#8]
```
What steps will reproduce the problem?

1. Paste tracker(s) in the Trackers List box
2. Update torrent

What is the expected output? What do you see instead?

Trackers should be added in the order they are listed in the Trackers List box 
(or in  add_trackers.txt). Instead the trackers are rearranged by alphabetical 
order casusing the primary tracker to be changed (the one scraped by default 
when the torrent is opened).

What version of the product are you using? On what operating system?

Using v1.31 on Windows 8.1 64-bit.

Please provide any additional information below.

For example let us say I have a torrent with tracker.ccc.de and 10.rarbg.com 
where tracker.ccc.de is the primary tracker. If I then add open.demonii.com, 
the tracker list is rearranged in alphabetical order with 10.rarbag.com 
becoming the new primary. If it is not possible to maintain the original order 
of the entire tracker list then please add a method to specify which tracker is 
the primary tracker. Maybe make the first tracker in the list the primary? The 
TorrentEditor website preserves the original order in which you add the 
trackers.

```

Original issue reported on code.google.com by `saigo...@gmail.com` on 4 Mar 2015 at 6:47

**Comment by Uplink10** [comment]
I can confirm this issue. Trackers should be added by the order they are listed in the "add_trackers.txt" because it is important that "Tier" does not change. If you have a tracker which is "Tier 1" in "add_trackers.txt" it should also be "Tier 1" in ".torrent" file.

**Comment by student13371** [comment]
I also confirm this issue.

There should be an option (or default behavior) that adds trackers not alphabetically, but in the same order trackers are listed in the Trackers List box or in  add_trackers.txt file.

Thank you for this amazing and very handy software. I've fixed thousands of .torrent files with your program.

**Comment by GerryFerdinandus** [comment]
Thanks for reporting this issue.
A new 1.32.beta version can be downloaded.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by student13371** [comment]
Issue seems to be solved. Tracker list order is preserved.

Users should keep in mind that "Present trackers in all torrent files" box still lists the trackers alphabetically (it's not a bug):

<img width="328" alt="order" src="https://cloud.githubusercontent.com/assets/12573989/9288059/d8947ec6-433c-11e5-97eb-ed594810717d.png">

However, preferred trackers order is preserved as shown in torrent client:

<img width="243" alt="order 2" src="https://cloud.githubusercontent.com/assets/12573989/9288065/0dedf0e8-433d-11e5-8001-4ba5e4ce2178.png">

Thank you.
