### ISSUE TITLE
Cannot add https tracker!

### ISSUE THREAD

**Issue by giibsii** [GerryFerdinandus/bittorrent-tracker-editor#9]
Hi there,
Your software tells me, when i edit multiple torrents to the same tracker address, the address HAS to be http:// (or udp://) and not https:// ... Why the distinction? What protection does this check even apply? It is very common nowadays for https tracker, please allow?
Much grattitude,
Is good software cos not all clients allow multiple torrent editting!

**Comment by GerryFerdinandus** [comment]
Thanks for reporting this issue.
A new 1.32.beta version can be downloaded.

Please test/verify/report back.
So that this issue report can be closed.

**Comment by student13371** [comment]
Issue solved.

https:// trackers are supported and can be added.

**Comment by giibsii** [comment]
Sorry for late reply and lack of any contribution on my part. Thank you for update!,

Consider bug fixed/feature added?

Thanks once agian

**Comment by student13371** [comment]
**giibsii**, since you've started this issue, you have the right to close this issue.

Click on **Close issue**:

<img width="530" alt="2015-08-24_13-05-37" src="https://cloud.githubusercontent.com/assets/12573989/9437801/b2202020-4a61-11e5-8089-ec375a428a95.png">
